# Generated by Django 4.2.5 on 2023-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.FilePathField(max_length=200, path='/')),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=200)),
                ('file_date', models.DateTimeField(verbose_name='date published')),
                ('file_hash', models.CharField(max_length=200)),
            ],
        ),
    ]
