# Generated by Django 4.2.5 on 2024-03-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0002_fileinsystem_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSystemFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('files_updated', models.IntegerField()),
            ],
        ),
    ]
