# Generated by Django 4.2.5 on 2024-03-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collect_files", "0003_updatesystemfiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_name", models.CharField(max_length=200)),
                ("order", models.IntegerField()),
                ("project", models.CharField(max_length=200)),
                ("bioproject", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
                ("species", models.CharField(max_length=200)),
                ("interest", models.CharField(max_length=200)),
                ("ngs_instrument", models.CharField(max_length=200)),
                ("read_size", models.CharField(max_length=200)),
                ("run_data", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="fileinsystem",
            name="sample",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collect_files.systemsample",
            ),
        ),
    ]
