# Generated by Django 4.2.5 on 2024-03-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0004_systemsample_fileinsystem_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinsystem',
            old_name='sample',
            new_name='system_sample',
        ),
        migrations.RemoveField(
            model_name='systemsample',
            name='run_data',
        ),
        migrations.AddField(
            model_name='systemsample',
            name='accession_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsample',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='systemsample',
            name='published_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsample',
            name='run_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsample',
            name='storage_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='bioproject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='interest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='ngs_instrument',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='project',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='read_size',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='species',
            field=models.CharField(default='', max_length=200),
        ),
    ]
