# Generated by Django 4.2.5 on 2024-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0005_rename_sample_fileinsystem_system_sample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSystemSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('samples_updated', models.IntegerField()),
            ],
        ),
    ]
