# Generated by Django 4.2.5 on 2024-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0006_updatesystemsamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsample',
            name='run_date_str',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsample',
            name='run_date',
            field=models.DateTimeField(default='', verbose_name='date published'),
        ),
    ]
