# Generated by Django 4.2.5 on 2024-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0007_systemsample_run_date_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsample',
            name='run_date',
            field=models.DateField(),
        ),
    ]
