# Generated by Django 4.2.5 on 2024-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0008_alter_systemsample_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsample',
            name='run_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
