# Generated by Django 4.2.5 on 2024-05-21 13:44

import collect_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0009_alter_systemsample_run_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatesystemfiles',
            name='files_updated',
        ),
        migrations.AddField(
            model_name='updatesystemfiles',
            name='contact',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='updatesystemfiles',
            name='file',
            field=models.FileField(default=None, upload_to=collect_files.models.generate_filename),
        ),
        migrations.AddField(
            model_name='updatesystemfiles',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='updatesystemfiles',
            name='is_fulfilled',
            field=models.BooleanField(default=None),
        ),
    ]
