# Generated by Django 4.2.5 on 2024-05-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect_files', '0009_alter_systemsample_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsample',
            name='fastq_file_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fileinsystem',
            name='system_sample',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='collect_files.systemsample'),
        ),
    ]
