# Generated by Django 4.2.5 on 2024-05-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsaflAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsafluMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('deprecated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InsafluProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_files.insaflaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TelevirSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('sample_name', models.CharField(max_length=100)),
                ('file_r1', models.CharField(max_length=100)),
                ('file_r2', models.CharField(max_length=100)),
                ('machine', models.ManyToManyField(to='process_files.insaflumachine')),
                ('project', models.ManyToManyField(to='process_files.insafluproject')),
            ],
        ),
        migrations.AddField(
            model_name='insaflaccount',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_files.insaflumachine'),
        ),
    ]
