# Generated by Django 4.2.5 on 2024-05-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsaflAccount',
            new_name='InsafluAccount',
        ),
    ]
