# Generated by Django 4.2.5 on 2024-05-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_files', '0003_remove_televirsample_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televirsample',
            name='account',
        ),
        migrations.AddField(
            model_name='televirsample',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='process_files.insafluaccount'),
        ),
    ]
